id: cce1e9e401ca4c3db5c03615d12a99c9
initial_creation_type: ocr
source_metadata:
  volumes:
    e3c31413c5c945018f857ee33bd69c43:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ཆོས་ཀྱི་དབྱིངས་ལྟ་བའི་གླུ།
      total_pages: 1902
      volume_number: 26
